# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'MySite'
- task: Npm@1
  displayName: 'webpack build'
  inputs:
    command: custom
    workingDir: 'MySite'
    customCommand: 'run buildProd'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/MySite.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/MySite'
    zipAfterPublish: true
    modifyOutputPath: false
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'MySite'
    publishLocation: 'Container'
